### ISSUE TITLE
Windows Folder missing ?

### ISSUE THREAD

**Issue by front-a-little** [SAP/mobilesdk-certificateprovider#4]
[This article here](http://help.sap.com/saphelp_smp309sdk/helpdata/en/6f/54ef9b3b1348b9a77fddec00362da1/content.htm) references this repo as source for a Windows Sample Project. However, non of the mentioned folders is present.

**Comment by sstadelman** [comment]
Windows snippets have been added.  Not sure what sample was intended to be referenced in this document, but please review the new examples.
